# Generated by Django 2.2.1 on 2019-05-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190509_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
    ]
